# **데이터 전처리**
* 목표 : 여행자와 여행지 seq 시계열 모델 학습용 분리

## 0. Import & Setting

In [51]:
import os 
import pandas as pd 
from pathlib import Path
from IPython.display import display, Markdown

In [3]:
ROOT_PATH = Path.cwd().parent
DATA_PATH = ROOT_PATH/"data"
CENTRAL_PATH = DATA_PATH/"raw/central/145.국내 여행로그 데이터_수도권_2차년도/3.개방데이터/1.데이터/Training/02.라벨링데이터/TL_CSV/"
EAST_PATH = DATA_PATH/"raw/east/146.국내 여행로그 데이터_동부권_2차년도/3.개방데이터/1.데이터/Training/02.라벨링데이터/TL_CSV/"
WEST_PATH = DATA_PATH/"raw/west/147.국내 여행로그 데이터_서부권_2차년도/3.개방데이터/1.데이터/Training/02.라벨링데이터/TL_CSV/"

assert all(path.exists() and len(list(path.iterdir()))==14 \
    for path in [CENTRAL_PATH,EAST_PATH,WEST_PATH]),\
    "경로 오류 또는 csv 파일 불일치"

In [ ]:
# 컬럼 이름 맞춰서 3개 df 통합시켜서 분석 가능한가? TRAVEL_ID 안겹치는지 확인
move_df_E = pd.read_csv(CENTRAL_PATH/"tn_move_his_이동내역_E.csv")
move_df_F = pd.read_csv(EAST_PATH/"tn_move_his_이동내역_F.csv")
move_df_G = pd.read_csv(WEST_PATH/"tn_move_his_이동내역_G.csv")

# 각 df의 TRAVEL_ID 집합 생성
travel_ids_E = set(move_df_E["TRAVEL_ID"].dropna().unique())
travel_ids_F = set(move_df_F["TRAVEL_ID"].dropna().unique())
travel_ids_G = set(move_df_G["TRAVEL_ID"].dropna().unique())

# 세 df 모두에 동시에 존재하는 TRAVEL_ID
common_all = travel_ids_E & travel_ids_F & travel_ids_G

# 두 개 이상 df에 중복으로 존재하는 TRAVEL_ID
duplicated_ids = (
    (travel_ids_E & travel_ids_F)
    | (travel_ids_E & travel_ids_G)
    | (travel_ids_F & travel_ids_G)
)

assert not duplicated_ids, f"TRAVEL_ID 독립적이지 않음 {set(duplicated_ids)}"

In [ ]:
# 컬럼 이름 맞춰서 3개 df 통합시켜서 분석 가능한가? TRAVEL_ID 안겹치는지 확인
move_df_E = pd.read_csv(CENTRAL_PATH/"tn_move_his_이동내역_E.csv")
move_df_F = pd.read_csv(EAST_PATH/"tn_move_his_이동내역_F.csv")
move_df_G = pd.read_csv(WEST_PATH/"tn_move_his_이동내역_G.csv")

# 각 df의 TRAVEL_ID 집합 생성
travel_ids_E = set(move_df_E["TRAVEL_ID"].dropna().unique())
travel_ids_F = set(move_df_F["TRAVEL_ID"].dropna().unique())
travel_ids_G = set(move_df_G["TRAVEL_ID"].dropna().unique())

# 세 df 모두에 동시에 존재하는 TRAVEL_ID
common_all = travel_ids_E & travel_ids_F & travel_ids_G

# 두 개 이상 df에 중복으로 존재하는 TRAVEL_ID
duplicated_ids = (
    (travel_ids_E & travel_ids_F)
    | (travel_ids_E & travel_ids_G)
    | (travel_ids_F & travel_ids_G)
)

assert not duplicated_ids, f"TRAVEL_ID 독립적이지 않음 {set(duplicated_ids)}"

In [10]:
'''
central : E 
east : F
west : G 
'''

for file in list(WEST_PATH.iterdir()):
    print(file.name)

tn_lodge_consume_his_숙박소비내역_G.csv
tn_activity_consume_his_활동소비내역_G.csv
tn_activity_his_활동내역_G.csv
tn_mvmn_consume_his_이동수단소비내역_G.csv
tc_sgg_시군구코드.csv
tc_codea_코드A.csv
tn_adv_consume_his_사전소비내역_G.csv
tn_travel_여행_G.csv
tn_visit_area_info_방문지정보_G.csv
tn_companion_info_동반자정보_G.csv
tn_move_his_이동내역_G.csv
tn_tour_photo_관광사진_G.csv
tn_traveller_master_여행객 Master_G.csv
tc_codeb_코드B.csv

## 1. EDA

In [57]:
# 공용 함수 

'''
make_name_efg 
df_name을 efg별 csv 파일 경로로 확장시키는 함수 
'''

def make_name_efg(df_name:str):
    e_path = CENTRAL_PATH/(df_name+"_E.csv")
    f_path = EAST_PATH/(df_name+"_F.csv")
    g_path = WEST_PATH/(df_name+"_G.csv")
    
    return e_path,f_path,g_path

'''
print_col_efg 
df_name을 가지는 df를 e,f,g 출력하는 함수

df_name : csv 확장자 제외한 파일 이름 
''' 
def print_col_efg(df_name:str):
    
    e_path,f_path,g_path = make_name_efg(df_name)
    
    e_df = pd.read_csv(e_path)
    f_df = pd.read_csv(f_path)
    g_df = pd.read_csv(g_path)
    
    if(e_df.columns.equals(f_df.columns) and f_df.columns.equals(g_df.columns)): 
        display(Markdown(f"### ===EFG 공통 : {df_name}==="))
        print(e_df.columns)
    else:
        display(Markdown(f"### ==={df_name}==="))
        common_cols = set(e_df.columns) & set(f_df.columns) & set(g_df.columns)
        all_cols = set(e_df.columns) | set(f_df.columns) | set(g_df.columns)
        print(f"교집합 컬럼 : {common_cols}")
        print(f"차집합 컬럼 : {all_cols-common_cols}")
        
'''
concat_efg 
컬럼이 모두 같은 3개의 EFG 파일 통합시키는 메서드 

df_name : csv 확장자 제외한 파일 이름 
'''
def concat_efg(df_name:str):
    e_path,f_path,g_path = make_name_efg(df_name)
        
    e_df = pd.read_csv(e_path)
    f_df = pd.read_csv(f_path)
    g_df = pd.read_csv(g_path)
    
    total_df = pd.concat([e_df,f_df,g_df],
                         axis = 0, 
                         ignore_index = True)
    
    return total_df

### (0) 병합 필요 여부 검사
- CODE A, B는 여행 특성, 방문 목적 등을 코드로 분류한 표기표로 W,E,C 모두 동일 -> 병합할 필요 없음
- SGG CODE 또한 동일 -> 병합 필요 없음 
- 그 외 여행 데이터 csv는 모두 TRAVEL ID를 기준으로 구분됨

#### (a) CODE A, B, SGG

In [62]:
## 코드 A 데이터를 병합할 필요가 있을지 확인 

c_codea_df = pd.read_csv(CENTRAL_PATH/"tc_codea_코드A.csv")
w_codea_df = pd.read_csv(WEST_PATH/"tc_codea_코드A.csv") 
e_codea_df = pd.read_csv(EAST_PATH/"tc_codea_코드A.csv")

## cd_nm이 모두 동일하다면 굳이 병합할 필요 없음
c_cd_nm = set(c_codea_df["cd_nm"].unique())
w_cd_nm = set(w_codea_df["cd_nm"].unique())
e_cd_nm = set(e_codea_df["cd_nm"].unique())

assert c_cd_nm == w_cd_nm and c_cd_nm == e_cd_nm,\
    "cd_nm 동일하지 않음"

print(c_cd_nm)

{'여행빈도_기간', '최종학력이수여부', '추천의향 점수', '여행종류', '여행동기', '직업기타', '소득', '메타데이터 진행상태', '방문선택이유', '여행동반자관계', '취식 지출 여부', '동반자동반상황', '여행스타일', '전반적 만족도 점수', '최종학력', '결제 방식', '주요 이동수단', '혼인상태', '성별', '방문활동', '방문지유형코드', '재방문 의향 점수', '여행상태', '동반자연령대', '미션', '직업', '여행권역', '재방문여부', '숙소유형', '입장료구분'}

In [63]:
c_codea_df.head()

,idx,cd_a,cd_nm,cd_memo,cd_memo2,del_flag,order_num,perm_write,perm_edit,perm_delete,ins_dt,edit_dt
0,5,STA,여행상태,NaN,NaN,N,999,N,N,N,2022-07-05 10:33:02,NaN
1,6,VIS,방문지유형코드,NaN,NaN,N,999,N,N,N,2022-07-05 10:45:53,NaN
2,7,MOV,주요 이동수단,NaN,NaN,N,999,N,N,N,2022-07-05 10:48:39,NaN
3,8,REV,재방문여부,NaN,NaN,N,999,N,N,N,2022-07-05 11:27:33,NaN
4,9,REN,방문선택이유,NaN,NaN,N,999,N,N,N,2022-07-05 11:28:18,NaN

In [67]:
c_codea_df[c_codea_df["cd_a"]=="MIS"]

,idx,cd_a,cd_nm,cd_memo,cd_memo2,del_flag,order_num,perm_write,perm_edit,perm_delete,ins_dt,edit_dt
14,19,MIS,미션,"여행테이블 여행목적, 여행미션에서 사용",NaN,N,999,N,N,N,2022-07-27 16:26:46,NaN

In [64]:
## 코드 B 데이터를 병합할 필요가 있을지 확인 

c_codeb_df = pd.read_csv(CENTRAL_PATH/"tc_codeb_코드B.csv")
w_codeb_df = pd.read_csv(WEST_PATH/"tc_codeb_코드B.csv") 
e_codeb_df = pd.read_csv(EAST_PATH/"tc_codeb_코드B.csv")

## cd_nm이 모두 동일하다면 굳이 병합할 필요 없음
c_cd_nm = set(c_codeb_df["cd_nm"].unique())
w_cd_nm = set(w_codeb_df["cd_nm"].unique())
e_cd_nm = set(e_codeb_df["cd_nm"].unique())

assert c_cd_nm == w_cd_nm and c_cd_nm == e_cd_nm,\
    "cd_nm 동일하지 않음"
print(c_cd_nm)

{'수료', '경남', '제주', '자연관광지', '장치․기계 조작 및 조립 종사자', '콘도미니엄/리조트', '월평균 100만원 ~ 200만원 미만', '렌터카(승용/승합/버스 등등)', '사별', '보통', '쇼핑', '일상적인 환경 및 역할에서의 탈출, 지루함 탈피', '캠핑카(자차 및 렌탈)', '현금', '시외/고속버스', '야외 스포츠, 레포츠 활동', '기능원 및 관련 기능 종사자', '도시 선호 매우선호', '전통 숙박시설', '캠핑', '취식', '1주일 ', '환승/경유', '지나가다 우연히', '휴식', '기타 활동', '매우 그렇다', '운동, 건강 증진 및 충전', '항공기', '이 방문지로 이동 중 구매/ 이 방문지로 배달', '새로운 경험 추구', '지역 축제/행사', '산책로, 둘레길 등', '월평균 600만원 ~ 700만원 미만', '반려동물 동반 여행', '택시', '관리자', '여자', '경북', '도서지역', '사진 업로드 전', '여행 출발 전 거주지 인근에서 미리 구매', '상점', '과거 경험이 좋아서', '강원', '호캉스 여행', '승인 거절', '자연 선호 중간선호', '농림어업 숙련 종사자', '친인척', '여행 후(기록전)', '매우 불만족', '교육/체험 프로그램 참가', 'Well-ness 여행', '교육성이 좋아서', '인플루언서 따라하기 여행', '버스 + 지하철', '예정여행지변경신청', '충북', '친구', '가성비가 좋아서', '연인', '1년', '최초 로그인', '배우자', '~9세이하', '월평균 900만원 ~ 1,000만원 미만', '월평균 700만원 ~ 800만원 미만', '지명도/명소/핫플레이스', '불만족', '20대', '전혀 그렇지 않다', '여행 중', '시티투어', '친목 단체/모임(동호회, 종교단체 등)', '승인 진행 중', '여행 기록 보완 완료', '대학교(4년제 이상)', '여행 중 이탈', '기타', '단순노무종사자', '가기 편해서/교통이 좋아서', '10대', '무학', '소득없음 ', '형제/자매', '자연 선호 매우선호', '중퇴', '졸업', '자연휴양림내 시설', '드라마 촬영지 방문', '여행 동반자와의 친밀감 및 유대감 증진', '한달', '고등학교', '비용 발생하지 않음 ', '대학원 박사 과정', '지역 축제/이벤트 참가', '자연 선호 약간선호', '친환경 여행(플로깅 여행)', '체험 활동 / 입장 및 관람', '기혼', 'SNS 인생샷 여행', '테스트 사진 업로드', '전남', '30대', '지역 문화예술/공연/전시시설 관람', '특별한 목적(칠순여행, 신혼여행, 수학여행, 인센티브여행)', '가족/친지집', '전업주부', '도시 선호 약간선호', '판매 종사자', '숙소', '등반 여행', '울산', '월평균 500만원 ~ 600만원 미만', 'KTX/SRT(고속열차)', '월평균 300만원 ~ 400만원 미만', '역사 탐방, 문화적 경험 등 교육적 동기', '테마파크, 놀이시설, 동/식물원 방문', '관광버스', '초등학교', '역, 터미널, 고속도로 휴게소', '대전', '경기', '50대', '상업지구(거리, 시장, 쇼핑시설)', '역사 유적지 방문', '모텔/여관', '새마을/무궁화열차', '자전거', '도시 선호 중간선호', '계좌이체', '체험', '남자', '그렇다', '단순 구경 / 산책 / 걷기', '편의시설/서비스가 좋아서', '서울', '신규 여행지 발굴', '도보', '예정여행지변경승인', '미디어(TV 정보 프로그램 등) 평가가 좋아서', '호텔', '쉴 수 있는 기회, 육체 피로 해결 및 정신적인 휴식', '비용 발생하지 않음(취식이 아닌 경우)', '사무실', '자가용(승용/승합/트럭 등등)', '여행 기록 입력 중', '역사/유적/종교 시설(문화재, 박물관, 촬영지, 절 등)', '문화 시설(공연장, 영화관, 전시관 등)', '여행 기록 입력 완료', '온천/스파', '40대', '학생', '배/선박', '그렇지 않다', '자녀', '계속 함께 여행', '없음', '월평균 100만원 미만', '서비스 종사자', '이 방문지에서 구매', '군인', '재학', 'SNS 사진 등록 등 과시', '70세이상', '카드 할부', '매우만족', '종교/성지 순례', '미혼', '사무 종사자', '입장 및 관람', '시내/마을버스', '대학(4년제 미만)', '세종', '휴학', '쇼핑 / 구매', '전북', '조부모', '레저/스포츠 관련 시설(스키, 카트, 수상레저)', '60대', '펜션', '진정한 자아 찾기 또는 자신을 되돌아볼 기회 찾기', '만족', '유흥/오락(나이트라이프)', '처음 방문', '야영(캠핑,글램핑등)', '온라인(SNS, 블로그 등) 평가가 좋아서', '여행 중 합류', '대학원 석사 과정', '대구', '식당/카페', '승인 완료', '재방문', '광주', '집', '카드 일시불', '월평균 800만원 ~ 900만원 미만', '인천', '부산', '부모', '지하철', '여행 기록 보완 요청', '월평균 200만원 ~ 300만원 미만', '이혼', '고속전철(ITX 등)', '테마시설(놀이공원, 워터파크)', '무박 여행', '민박', '친구/친지집', '체험 활동 관광지', '월평균 1,000만원 이상', '전문가 및 관련 종사자', '월평균 400만원 ~ 500만원 미만', '게스트하우스', '중립', '동료', '충남', '중학교', '지인의 추천이 있어서'}

In [65]:
c_codeb_df.head()

,idx,cd_a,cd_b,cd_nm,cd_memo,cd_memo2,del_flag,order_num,ins_dt,edit_dt
0,1055,ACT,1,취식,NaN,NaN,N,10,2022-07-05 11:34:29,NaN
1,1056,ACT,2,쇼핑 / 구매,(아이 쇼핑 포함)<br>* 이전 방문지에서 해당 방문지 이동 중 구매한 내역 포함,NaN,N,20,2022-07-05 11:49:08,NaN
2,1057,ACT,3,체험 활동 / 입장 및 관람,NaN,NaN,N,30,2022-07-05 11:49:37,NaN
3,1058,ACT,4,단순 구경 / 산책 / 걷기,NaN,NaN,N,40,2022-07-05 11:49:43,NaN
4,1059,ACT,5,휴식,NaN,NaN,N,50,2022-07-05 11:49:48,NaN

In [73]:
c_codeb_df[c_codeb_df["cd_a"]=="MIS"]

,idx,cd_a,cd_b,cd_nm,cd_memo,cd_memo2,del_flag,order_num,ins_dt,edit_dt
95,1097,MIS,1,쇼핑,NaN,NaN,N,999,2022-07-27 16:26:52,NaN
96,1098,MIS,2,"테마파크, 놀이시설, 동/식물원 방문",NaN,NaN,N,999,2022-07-27 16:26:58,NaN
97,1099,MIS,3,역사 유적지 방문,NaN,NaN,N,999,2022-07-27 16:27:03,NaN
98,1100,MIS,4,시티투어,NaN,NaN,N,999,2022-07-27 16:27:08,NaN
99,1101,MIS,5,"야외 스포츠, 레포츠 활동",NaN,NaN,N,999,2022-07-27 16:27:14,NaN
100,1102,MIS,6,지역 문화예술/공연/전시시설 관람,NaN,NaN,N,999,2022-07-27 16:27:19,NaN
101,1103,MIS,7,유흥/오락(나이트라이프),NaN,NaN,N,999,2022-07-27 16:27:26,NaN
102,1104,MIS,8,캠핑,NaN,NaN,N,999,2022-07-27 16:27:31,NaN
103,1105,MIS,9,지역 축제/이벤트 참가,NaN,NaN,N,999,2022-07-27 16:27:37,NaN
104,1106,MIS,10,온천/스파,NaN,NaN,N,999,2022-07-27 16:27:43,NaN
105,1107,MIS,11,교육/체험 프로그램 참가,NaN,NaN,N,999,2022-07-27 16:27:48,NaN
106,1108,MIS,12,드라마 촬영지 방문,NaN,NaN,N,999,2022-07-27 16:27:57,NaN
107,1109,MIS,13,종교/성지 순례,NaN,NaN,N,999,2022-07-27 16:28:01,NaN
108,1110,MIS,21,Well-ness 여행,NaN,NaN,N,999,2022-07-27 16:28:07,NaN
109,1111,MIS,22,SNS 인생샷 여행,NaN,NaN,N,999,2022-07-27 16:28:11,NaN
110,1112,MIS,23,호캉스 여행,NaN,NaN,N,999,2022-07-27 16:28:16,NaN
111,1113,MIS,24,신규 여행지 발굴,NaN,NaN,N,999,2022-07-27 16:28:21,NaN
112,1114,MIS,25,반려동물 동반 여행,NaN,NaN,N,999,2022-07-27 16:28:26,NaN
113,1115,MIS,26,인플루언서 따라하기 여행,NaN,NaN,N,999,2022-07-27 16:28:34,NaN
114,1116,MIS,27,친환경 여행(플로깅 여행),NaN,NaN,N,999,2022-07-27 16:30:10,NaN
115,1117,MIS,28,등반 여행,NaN,NaN,N,999,2022-07-27 16:30:13,NaN

In [62]:
## 코드 B 데이터를 병합할 필요가 있을지 확인 

c_sgg_df = pd.read_csv(CENTRAL_PATH/"tc_sgg_시군구코드.csv")
w_sgg_df = pd.read_csv(WEST_PATH/"tc_sgg_시군구코드.csv") 
e_sgg_df = pd.read_csv(EAST_PATH/"tc_sgg_시군구코드.csv")

## cd_nm이 모두 동일하다면 굳이 병합할 필요 없음
c_sgg = set(c_sgg_df["SGG_CD"].unique())
w_sgg = set(w_sgg_df["SGG_CD"].unique())
e_sgg = set(e_sgg_df["SGG_CD"].unique())

assert c_sgg == w_sgg and c_sgg == e_sgg,\
    "시군구 코드 동일하지 않음"
print(c_sgg)

{np.int64(4617011200), np.int64(2771025921), np.int64(2771025922), np.int64(2771025923), np.int64(1114013700), np.int64(2771025924), np.int64(2771025925), np.int64(2771025926), np.int64(2771025927), np.int64(2771025928), np.int64(2771025929), np.int64(2771025930), np.int64(2771025931), np.int64(2771025932), np.int64(2771025933), np.int64(4215013400), np.int64(4219011100), np.int64(4812111900), np.int64(4159012900), np.int64(4163010600), np.int64(4611014700), np.int64(4615012400), np.int64(1120010300), np.int64(3023011900), np.int64(4128112700), np.int64(5011013700), np.int64(2826010700), np.int64(4217012300), np.int64(4729012300), np.int64(2911010900), np.int64(4678025300), np.int64(4613013600), np.int64(4617011300), np.int64(1114013800), np.int64(3171025000), np.int64(4678025321), np.int64(4678025322), np.int64(4575035500), np.int64(4678025323), np.int64(4678025324), np.int64(4678025325), np.int64(4678025326), np.int64(4678025327), np.int64(4678025329), np.int64(4678025330), np.int64(4420010100), np.int64(4678025331), np.int64(4678025332), np.int64(4678025333), np.int64(4519035000), np.int64(4678025334), np.int64(4678025335), np.int64(4678025336), np.int64(4215013500), np.int64(3171025021), np.int64(3171025022), np.int64(3171025023), np.int64(1138000000), np.int64(3171025024), np.int64(3171025025), np.int64(3171025026), np.int64(3171025027), np.int64(3171025028), np.int64(3171025029), np.int64(3171025030), np.int64(3171025031), np.int64(3171025032), np.int64(3171025033), np.int64(4159013000), np.int64(4163010700), np.int64(2871034000), np.int64(4611014800), np.int64(4615012500), np.int64(4782031000), np.int64(1120010400), np.int64(3023012000), np.int64(4128112800), np.int64(5011013800), np.int64(2826010800), np.int64(4217012400), np.int64(4729012400), np.int64(4221010100), np.int64(2911011000), np.int64(4183032000), np.int64(4613013700), np.int64(4617011400), np.int64(1114013900), np.int64(4420010200), np.int64(4882039000), np.int64(4215013600), np.int64(4219011300), np.int64(4812112100), np.int64(4159013100), np.int64(4163010800), np.int64(4611014900), np.int64(4615012600), np.int64(1120010500), np.int64(3023012100), np.int64(4128112900), np.int64(5011013900), np.int64(4521034000), np.int64(2826010900), np.int64(4217012500), np.int64(4729012500), np.int64(2771026200), np.int64(4221010200), np.int64(4683039000), np.int64(2911011100), np.int64(4413325600), np.int64(4613013800), np.int64(4617011500), np.int64(2771026221), np.int64(2771026222), np.int64(2771026223), np.int64(1114014000), np.int64(2771026224), np.int64(2771026225), np.int64(2771026226), np.int64(2771026227), np.int64(2771026228), np.int64(2771026229), np.int64(4571038000), np.int64(4420010300), np.int64(4125000000), np.int64(4215013700), np.int64(4219011400), np.int64(4812112200), np.int64(4159013200), np.int64(4163010900), np.int64(4611015000), np.int64(4615012700), np.int64(1120010600), np.int64(3023012200), np.int64(4128113000), np.int64(4423025000), np.int64(4888025021), np.int64(4884038000), np.int64(5011014000), np.int64(4136010100), np.int64(4888025022), np.int64(2826011000), np.int64(4217012600), np.int64(4729012600), np.int64(4888025023), np.int64(4221010300), np.int64(4423025021), np.int64(4423025022), np.int64(4423025023), np.int64(2911011200), np.int64(4423025024), np.int64(4423025025), np.int64(4423025026), np.int64(4423025027), np.int64(4423025028), np.int64(4423025029), np.int64(4423025030), np.int64(4423025031), np.int64(4423025032), np.int64(4423025033), np.int64(4888025025), np.int64(4613013900), np.int64(4888025026), np.int64(3611034000), np.int64(4617011600), np.int64(1114014100), np.int64(3171025300), np.int64(4148036000), np.int64(4420010400), np.int64(4215013800), np.int64(3171025321), np.int64(3171025322), np.int64(3171025323), np.int64(3171025324), np.int64(3171025325), np.int64(3171025326), np.int64(3171025327), np.int64(3171025328), np.int64(3171025329), np.int64(3171025330), np.int64(3171025331), np.int64(3171025332), np.int64(3171025333), np.int64(3171025334), np.int64(3171025335), np.int64(4163011000), np.int64(4159013300), np.int64(4611015100), np.int64(4615012800), np.int64(1120010700), np.int64(3023012300), np.int64(4128113100), np.int64(4136010200), np.int64(2826011100), np.int64(4217012700), np.int64(4679041500), np.int64(4729012700), np.int64(4221010400), np.int64(2911011300), np.int64(4613014000), np.int64(2714010100), np.int64(4617011700), np.int64(1114014200), np.int64(4420010500), np.int64(4374037000), np.int64(4886037000), np.int64(4215013900), np.int64(4219011600), np.int64(4812112400), np.int64(4159013400), np.int64(4163011100), np.int64(4611015200), np.int64(4615012900), np.int64(1120010800), np.int64(3023012400), np.int64(4128113200), np.int64(4150035000), np.int64(4136010300), np.int64(2826011200), np.int64(4217012800), np.int64(4729012800), np.int64(2771026500), np.int64(4221010500), np.int64(2911011400), np.int64(4687037000), np.int64(4613014100), np.int64(2714010200), np.int64(2771026521), np.int64(2771026522), np.int64(2771026523), np.int64(1114014300), np.int64(2771026524), np.int64(2771026525), np.int64(2771026526), np.int64(2771026527), np.int64(2771026529), np.int64(2771026530), np.int64(2771026531), np.int64(2771026528), np.int64(4575036000), np.int64(4420010600), np.int64(4219011700), np.int64(4812112500), np.int64(4159013500), np.int64(4163011200), np.int64(4611015300), np.int64(4615013000), np.int64(1120010900), np.int64(3023012500), np.int64(4423025300), np.int64(4513039000), np.int64(4136010400), np.int64(4376036000), np.int64(4482532000), np.int64(4888036000), np.int64(2826011300), np.int64(4217012900), np.int64(4221010600), np.int64(4423025321), np.int64(4423025322), np.int64(4423025323), np.int64(2911011500), np.int64(4423025324), np.int64(4423025325), np.int64(4423025326), np.int64(4423025327), np.int64(4423025328), np.int64(4423025329), np.int64(4423025330), np.int64(4165010100), np.int64(4423025331), np.int64(4423025332), np.int64(4423025333), np.int64(4613014200), np.int64(4776035000), np.int64(4792025022), np.int64(4792025023), np.int64(2714010300), np.int64(4617011900), np.int64(4792025024), np.int64(1114014400), np.int64(3171025600), np.int64(4792025025), np.int64(4792025026), np.int64(4420010700), np.int64(4792025027), np.int64(4792025028), np.int64(3171025621), np.int64(3171025622), np.int64(3171025623), np.int64(3171025624), np.int64(3171025625), np.int64(3171025626), np.int64(3171025627), np.int64(3171025628), np.int64(3171025629), np.int64(3171025630), np.int64(4792025029), np.int64(4111500000), np.int64(4159013600), np.int64(4476044000), np.int64(4689036000), np.int64(4163011300), np.int64(4792025030), np.int64(4792025031), np.int64(4611015400), np.int64(4615013100), np.int64(1120011000), np.int64(3023012600), np.int64(4577035000), np.int64(4136010500), np.int64(2826011400), np.int64(4217013000), np.int64(4221010700), np.int64(2911011600), np.int64(4165010200), np.int64(4613014300), np.int64(2714010400), np.int64(4117300000), np.int64(4617012000), np.int64(1114014500), np.int64(4420010800), np.int64(4812112700), np.int64(4159013700), np.int64(4163011400), np.int64(4611015500), np.int64(4615013200), np.int64(1120011100), np.int64(4372038500), np.int64(4136010600), np.int64(2826011500), np.int64(4217013100), np.int64(4221010800), np.int64(2911011700), np.int64(4691035000), np.int64(4165010300), np.int64(4613014400), np.int64(2714010500), np.int64(4617012100), np.int64(1114014600), np.int64(4579034000), np.int64(4420010900), np.int64(4159013800), np.int64(4680025000), np.int64(4163011500), np.int64(4611015600), np.int64(4615013300), np.int64(4680025021), np.int64(4680025022), np.int64(4680025023), np.int64(1111000000), np.int64(1120011200), np.int64(2647000000), np.int64(4146136000), np.int64(4183000000), np.int64(4680025024), np.int64(4680025025), np.int64(4680025026), np.int64(4680025027), np.int64(4680025028), np.int64(4680025029), np.int64(4680025030), np.int64(4680025031), np.int64(4680025032), np.int64(4680025033), np.int64(4680025034), np.int64(4217013200), np.int64(4380034000), np.int64(4679042000), np.int64(4680025035), np.int64(4221010900), np.int64(4680025037), np.int64(4680025038), np.int64(4680025039), np.int64(2911011800), np.int64(4680025040), np.int64(4680025041), np.int64(4680025042), np.int64(4680025043), np.int64(4680025044), np.int64(4680025045), np.int64(4680025046), np.int64(4165010400), np.int64(4680025048), np.int64(4613014500), np.int64(2714010600), np.int64(4481025000), np.int64(4617012200), np.int64(1114014700), np.int64(3171025900), np.int64(4420011000), np.int64(4481025021), np.int64(4481025022), np.int64(4481025023), np.int64(4481025024), np.int64(3171025921), np.int64(3171025922), np.int64(3171025923), np.int64(3171025924), np.int64(3171025925), np.int64(3171025926), np.int64(3171025927), np.int64(3171025928), np.int64(3171025929), np.int64(3171025930), np.int64(4481025033), np.int64(4159013900), np.int64(4481025028), np.int64(4481025029), np.int64(4481025030), np.int64(4163011600), np.int64(4481025032), np.int64(4611015700), np.int64(1120011300), np.int64(4282025000), np.int64(4794025000), np.int64(4136010800), np.int64(2826011700), np.int64(4217013300), np.int64(4617010600), np.int64(4221011000), np.int64(2911011900), np.int64(4282025021), np.int64(4282025022), np.int64(4282025023), np.int64(4282025024), np.int64(4282025025), np.int64(4282025026), np.int64(4282025027), np.int64(4165010500), np.int64(4282025028), np.int64(4282025029), np.int64(4282025030), np.int64(4282025031), np.int64(4282025033), np.int64(4282025034), np.int64(4282025035), np.int64(2714010700), np.int64(4282025036), np.int64(4282025037), np.int64(4282025032), np.int64(1114014800), np.int64(4613014600), np.int64(4617012300), np.int64(4420011100), np.int64(4146300000), np.int64(4519036000), np.int64(4159014000), np.int64(4163011700), np.int64(2871035000), np.int64(4611015800), np.int64(4782032000), np.int64(1120011400), np.int64(4136010900), np.int64(2826011800), np.int64(4217013400), np.int64(4221011100), np.int64(2911012000), np.int64(2629010600), np.int64(4165010600), np.int64(4183033000), np.int64(4613014700), np.int64(2714010800), np.int64(4617012400), np.int64(1114014900), np.int64(4420011200), np.int64(4882040000), np.int64(4680025300), np.int64(4471031000), np.int64(4611015900), np.int64(4680025321), np.int64(4680025322), np.int64(4680025323), np.int64(1120011500), np.int64(4680025324), np.int64(4680025325), np.int64(4680025326), np.int64(4680025327), np.int64(4680025328), np.int64(4680025329), np.int64(4680025330), np.int64(4680025331), np.int64(4680025332), np.int64(4680025333), np.int64(4680025334), np.int64(4136011000), np.int64(4521035000), np.int64(4680025335), np.int64(4680025336), np.int64(2826011900), np.int64(4217013500), np.int64(4221011200), np.int64(2911012100), np.int64(2629010700), np.int64(4613014800), np.int64(2714010900), np.int64(4481025300), np.int64(4617012500), np.int64(1114015000), np.int64(3171026200), np.int64(4272031000), np.int64(4571039000), np.int64(4784031000), np.int64(4420011300), np.int64(4481025321), np.int64(4481025322), np.int64(4481025323), np.int64(4481025324), np.int64(3171026221), np.int64(3171026222), np.int64(3171026223), np.int64(3171026224), np.int64(3171026225), np.int64(3171026226), np.int64(3171026227), np.int64(3171026228), np.int64(3171026229), np.int64(4223010100), np.int64(4481025329), np.int64(4481025330), np.int64(4481025333), np.int64(4481025334), np.int64(4481025331), np.int64(4481025332), np.int64(4481025341), np.int64(4481025335), np.int64(4481025336), np.int64(4481025337), np.int64(4481025338), np.int64(4481025339), np.int64(4481025340), np.int64(4611016000), np.int64(4282025300), np.int64(4372039000), np.int64(4884039000), np.int64(4136011100), np.int64(2826012000), np.int64(4217013600), np.int64(4221011300), np.int64(2911012200), np.int64(4282025321), np.int64(4282025322), np.int64(4282025323), np.int64(4282025324), np.int64(4282025325), np.int64(4282025326), np.int64(4282025327), np.int64(2629010800), np.int64(4282025328), np.int64(4282025329), np.int64(4282025330), np.int64(4282025331), np.int64(4282025332), np.int64(4282025333), np.int64(4282025334), np.int64(2714011000), np.int64(3611035000), np.int64(4282025335), np.int64(4282025336), np.int64(1114015100), np.int64(4282025337), np.int64(4617012600), np.int64(4148037000), np.int64(4420011400), np.int64(4223010200), np.int64(4482500000), np.int64(4611016100), np.int64(4611012300), np.int64(4136011200), np.int64(2826012100), np.int64(2911012300), np.int64(2629010900), np.int64(4613015000), np.int64(2714011100), np.int64(4617012700), np.int64(1114015200), np.int64(4420011500), np.int64(4374038000), np.int64(4886038000), np.int64(3114010100), np.int64(4223010300), np.int64(4680025600), np.int64(4611016200), np.int64(4680025621), np.int64(4680025622), np.int64(4680025623), np.int64(1120011800), np.int64(4680025624), np.int64(4680025625), np.int64(4680025626), np.int64(4680025627), np.int64(4680025628), np.int64(4680025629), np.int64(4150036000), np.int64(2826012200), np.int64(2911012400), np.int64(4687038000), np.int64(2629011000), np.int64(4613015100), np.int64(2714011200), np.int64(4617012800), np.int64(1114015300), np.int64(3171026500), np.int64(4575037000), np.int64(4420011600), np.int64(4812310100), np.int64(3114010200), np.int64(3171026521), np.int64(3171026522), np.int64(3171026523), np.int64(3171026524), np.int64(3171026525), np.int64(4223010400), np.int64(4611016300), np.int64(4513040000), np.int64(4376037000), np.int64(4482533000), np.int64(4888037000), np.int64(2911012500), np.int64(2629011100), np.int64(4812900000), np.int64(2714011300), np.int64(4617012900), np.int64(1114015400), np.int64(4420011700), np.int64(4812310200), np.int64(3114010300), np.int64(4223010500), np.int64(4476045000), np.int64(4689037000), np.int64(4611016400), np.int64(4415031000), np.int64(4812312900), np.int64(4577036000), np.int64(2911012600), np.int64(2620000000), np.int64(2714011400), np.int64(4617013000), np.int64(1114015500), np.int64(4420011800), np.int64(4728031000), np.int64(4812310300), np.int64(3114010400), np.int64(4677044000), np.int64(4223010600), np.int64(4167010100), np.int64(2911012700), np.int64(4113500000), np.int64(4691036000), np.int64(2714011500), np.int64(4617013100), np.int64(1114015600), np.int64(4579035000), np.int64(4420011900), np.int64(4782000000), np.int64(4812310400), np.int64(3114010500), np.int64(4223010700), np.int64(4167010200), np.int64(1120012200), np.int64(4380035000), np.int64(2911012800), np.int64(2714011600), np.int64(4617013200), np.int64(1114015700), np.int64(4812310500), np.int64(3114010600), np.int64(4223010800), np.int64(4167010300), np.int64(2911012900), np.int64(4682025000), np.int64(2714011700), np.int64(4617013300), np.int64(1114015800), np.int64(4682025021), np.int64(4682025022), np.int64(4682025023), np.int64(4682025024), np.int64(4682025025), np.int64(4682025026), np.int64(4682025027), np.int64(4682025028), np.int64(4682025029), np.int64(4682025030), np.int64(4682025031), np.int64(4519037000), np.int64(4682025032), np.int64(4682025033), np.int64(4682025034), np.int64(3114010700), np.int64(4682025035), np.int64(4682025036), np.int64(4682025037), np.int64(4682025038), np.int64(4812310600), np.int64(4223010900), np.int64(2871036000), np.int64(4167010400), np.int64(4782033000), np.int64(2911013000), np.int64(4183034000), np.int64(2714011800), np.int64(4617013400), np.int64(1114015900), np.int64(4882041000), np.int64(4812310700), np.int64(3114010800), np.int64(4223011000), np.int64(4471032000), np.int64(4167010500), np.int64(4521036000), np.int64(2911013100), np.int64(4822010100), np.int64(4413131000), np.int64(2714011900), np.int64(1114016000), np.int64(4100000000), np.int64(4272032000), np.int64(4571040000), np.int64(4784032000), np.int64(4812310800), np.int64(3114010900), np.int64(4672031000), np.int64(4223011100), np.int64(4167010600), np.int64(4623010100), np.int64(4372040000), np.int64(2911013200), np.int64(4822010200), np.int64(2714012000), np.int64(3611036000), np.int64(1114016100), np.int64(4148038000), np.int64(4812310900), np.int64(3114011000), np.int64(4223011200), np.int64(4167010700), np.int64(4623010200), np.int64(1153010100), np.int64(2911013300), np.int64(4822010300), np.int64(2714012100), np.int64(1114016200), np.int64(4374039000), np.int64(4812311000), np.int64(4886039000), np.int64(3114011100), np.int64(4223011300), np.int64(4313025000), np.int64(4825025000), np.int64(4167010800), np.int64(4623010300), np.int64(4313025021), np.int64(4313025022), np.int64(4313025023), np.int64(4313025024), np.int64(4313025025), np.int64(4313025026), np.int64(4313025027), np.int64(4313025028), np.int64(4313025029), np.int64(4313025030), np.int64(4313025031), np.int64(4150037000), np.int64(4825025024), np.int64(4825025025), np.int64(4825025026), np.int64(4825025027), np.int64(4825025028), np.int64(4825025029), np.int64(4825025030), np.int64(4825025031), np.int64(4825025032), np.int64(4825025033), np.int64(1153010200), np.int64(2911013400), np.int64(4822010400), np.int64(2714012200), np.int64(1114016300), np.int64(4575038000), np.int64(4812311100), np.int64(3114011200), np.int64(4129000000), np.int64(4223011400), np.int64(4167010900), np.int64(4623010400), np.int64(4427025000), np.int64(4482534000), np.int64(4888038000), np.int64(1153010300), np.int64(4427025021), np.int64(4427025022), np.int64(4427025023), np.int64(4427025024), np.int64(4427025025), np.int64(4427025026), np.int64(4427025027), np.int64(4427025028), np.int64(4427025029), np.int64(4427025030), np.int64(4427025031), np.int64(4427025032), np.int64(4427025033), np.int64(4427025034), np.int64(4822010500), np.int64(2714012300), np.int64(1114016400), np.int64(4812311200), np.int64(3114011300), np.int64(4223011500), np.int64(4689038000), np.int64(2917010100), np.int64(4167011000), np.int64(1171000000), np.int64(4415032000), np.int64(4623010500), np.int64(4790039000), np.int64(4577037000), np.int64(4822010800), np.int64(4822010600), np.int64(2714012400), np.int64(1114016500), np.int64(3020000000), np.int64(4728032000), np.int64(4812311300), np.int64(3114011400), np.int64(4677045000), np.int64(4223011600), np.int64(2917010200), np.int64(4167011100), np.int64(4623010600), np.int64(4691037000), np.int64(4822010700), np.int64(2714012500), np.int64(1114016600), np.int64(4579036000), np.int64(4812311400), np.int64(3114011500), np.int64(4223011700), np.int64(2917010300), np.int64(4167011200), np.int64(4623010700), np.int64(4427025300), np.int64(4380036000), np.int64(1153010600), np.int64(4427025321), np.int64(4427025322), np.int64(4427025323), np.int64(4427025324), np.int64(4427025325), np.int64(4427025326), np.int64(4427025327), np.int64(4427025328), np.int64(4427025329), np.int64(4427025330), np.int64(4427025331), np.int64(4427025332), np.int64(4427025333), np.int64(4427025334), np.int64(4427025335), np.int64(2714012600), np.int64(4374531000), np.int64(4427025337), np.int64(4427025339), np.int64(1114016700), np.int64(4427025338), np.int64(4427025341), np.int64(4427025342), np.int64(4471000000), np.int64(4427025336), np.int64(4427025340), np.int64(4812311500), np.int64(3114011600), np.int64(4223011800), np.int64(2917010400), np.int64(4167011300), np.int64(4623010800), np.int64(4272000000), np.int64(4784000000), np.int64(1153010700), np.int64(4822010900), np.int64(2714012700), np.int64(4711311200), np.int64(1114016800), np.int64(4519038000), np.int64(4812311600), np.int64(3114011700), np.int64(4223011900), np.int64(2917010500), np.int64(2871037000), np.int64(4167011400), np.int64(4782034000), np.int64(4623010900), np.int64(4127100000), np.int64(1153010800), np.int64(4183035000), np.int64(4822011000), np.int64(2714012800), np.int64(1114016900), np.int64(4882042000), np.int64(4812311700), np.int64(3114011800), np.int64(4223012000), np.int64(2917010600), np.int64(4471033000), np.int64(4684025000), np.int64(4167011500), np.int64(4623011000), np.int64(4684025021), np.int64(4684025022), n

#### (b) 여행 정보 
- tn_move_his_이동내역_E.csv
- tn_travel_여행_E.csv
- tn_activity_his_활동내역_E.csv
- tn_visit_area_info_방문지정보_E.csv

In [58]:
# 3개 csv의 컬럼 종류 파악하기 
# 이동내역 컬럼 
print_col_efg("tn_move_his_이동내역")
# 여행 컬럼 
print_col_efg("tn_travel_여행")
# 활동내역 컬럼 
print_col_efg("tn_activity_his_활동내역")
# 방문지 정보 
print_col_efg("tn_visit_area_info_방문지정보")

### ===EFG 공통 : tn_move_his_이동내역===

Index(['TRAVEL_ID', 'TRIP_ID', 'START_VISIT_AREA_ID', 'END_VISIT_AREA_ID',
       'START_DT_MIN', 'END_DT_MIN', 'MVMN_CD_1', 'MVMN_CD_2'],
      dtype='str')

### ===EFG 공통 : tn_travel_여행===

Index(['TRAVEL_ID', 'TRAVEL_NM', 'TRAVELER_ID', 'TRAVEL_PURPOSE',
       'TRAVEL_START_YMD', 'TRAVEL_END_YMD', 'MVMN_NM', 'TRAVEL_PERSONA',
       'TRAVEL_MISSION', 'TRAVEL_MISSION_CHECK'],
      dtype='str')

### ===EFG 공통 : tn_activity_his_활동내역===

Index(['TRAVEL_ID', 'VISIT_AREA_ID', 'ACTIVITY_TYPE_CD', 'ACTIVITY_TYPE_SEQ',
       'ACTIVITY_ETC', 'ACTIVITY_DTL', 'RSVT_YN', 'EXPND_SE', 'ADMISSION_SE'],
      dtype='str')

### ===EFG 공통 : tn_visit_area_info_방문지정보===

Index(['VISIT_AREA_ID', 'TRAVEL_ID', 'VISIT_ORDER', 'VISIT_AREA_NM',
       'VISIT_START_YMD', 'VISIT_END_YMD', 'ROAD_NM_ADDR', 'LOTNO_ADDR',
       'X_COORD', 'Y_COORD', 'ROAD_NM_CD', 'LOTNO_CD', 'POI_ID', 'POI_NM',
       'RESIDENCE_TIME_MIN', 'VISIT_AREA_TYPE_CD', 'REVISIT_YN',
       'VISIT_CHC_REASON_CD', 'LODGING_TYPE_CD', 'DGSTFN', 'REVISIT_INTENTION',
       'RCMDTN_INTENTION', 'SGG_CD'],
      dtype='str')

In [38]:
# 컬럼 이름 맞춰서 3개 df 통합시켜서 분석 가능한가? TRAVEL_ID 안겹치는지 확인
move_df_E = pd.read_csv(CENTRAL_PATH/"tn_move_his_이동내역_E.csv")
move_df_F = pd.read_csv(EAST_PATH/"tn_move_his_이동내역_F.csv")
move_df_G = pd.read_csv(WEST_PATH/"tn_move_his_이동내역_G.csv")

# 각 df의 TRAVEL_ID 집합 생성
travel_ids_E = set(move_df_E["TRAVEL_ID"].dropna().unique())
travel_ids_F = set(move_df_F["TRAVEL_ID"].dropna().unique())
travel_ids_G = set(move_df_G["TRAVEL_ID"].dropna().unique())

# 세 df 모두에 동시에 존재하는 TRAVEL_ID
common_all = travel_ids_E & travel_ids_F & travel_ids_G

# 두 개 이상 df에 중복으로 존재하는 TRAVEL_ID
duplicated_ids = (
    (travel_ids_E & travel_ids_F)
    | (travel_ids_E & travel_ids_G)
    | (travel_ids_F & travel_ids_G)
)

assert not duplicated_ids, f"TRAVEL_ID 독립적이지 않음 {set(duplicated_ids)}"

In [60]:
# E,F,G 통합시키기 
move_total_df = concat_efg("tn_move_his_이동내역")
display(Markdown("### 이동내역"))
display(move_total_df.head())

travel_total_df = concat_efg("tn_travel_여행")
display(Markdown("### 여행"))
display(travel_total_df.head())

activity_total_df = concat_efg("tn_activity_his_활동내역")
display(Markdown("### 활동내역"))
display(activity_total_df.head())

visit_area_total_df = concat_efg("tn_visit_area_info_방문지정보")
display(Markdown("### 방문지정보"))
display(visit_area_total_df.head())

### 이동내역

,TRAVEL_ID,TRIP_ID,START_VISIT_AREA_ID,END_VISIT_AREA_ID,START_DT_MIN,END_DT_MIN,MVMN_CD_1,MVMN_CD_2
0,e_e000004,2304300001,2.304300e+09,NaN,2023-04-30 13:30,NaN,NaN,NaN
1,e_e000004,2304300002,NaN,2.304300e+09,NaN,2023-04-30 14:00,1.0,NaN
2,e_e000004,2304300003,NaN,2.304300e+09,NaN,2023-04-30 15:00,15.0,NaN
3,e_e000004,2304300004,NaN,2.304300e+09,NaN,2023-04-30 15:30,15.0,NaN
4,e_e000004,2304300005,NaN,2.304300e+09,NaN,2023-04-30 17:30,1.0,NaN

### 여행

,TRAVEL_ID,TRAVEL_NM,TRAVELER_ID,TRAVEL_PURPOSE,TRAVEL_START_YMD,TRAVEL_END_YMD,MVMN_NM,TRAVEL_PERSONA,TRAVEL_MISSION,TRAVEL_MISSION_CHECK
0,e_e000004,E03,e000004,3,2023-04-30,2023-05-01,NaN,서울 외 수도권 방문/수도권 거주/40세 이상/자녀동반/일반미션,3,3;4;11
1,e_e000006,E03,e000006,21,2023-04-30,2023-05-02,NaN,경기 방문/거주지 구분 없음/39세 이하/특별미션,21,21;10;27
2,e_e000009,E03,e000009,2;4,2023-04-29,2023-05-01,NaN,서울 외 수도권 방문/수도권 거주/39세 이하/커플/일반미션,2;4,22;1;7
3,e_e000010,E01,e000010,3;6,2023-04-29,2023-05-01,NaN,서울 방문/수도권 외 거주/39세 이하/나홀로 여행/일반미션,3;6,6;3;1
4,e_e000011,E01,e000011,1;21,2023-04-28,2023-05-01,NaN,서울 방문/수도권 외 거주/40세 이상/커플/일반미션,1;21,6;2;24

### 활동내역

,TRAVEL_ID,VISIT_AREA_ID,ACTIVITY_TYPE_CD,ACTIVITY_TYPE_SEQ,ACTIVITY_ETC,ACTIVITY_DTL,RSVT_YN,EXPND_SE,ADMISSION_SE
0,e_e000004,2304300002,3,0,NaN,화성 어차 탑승,Y,5,1.0
1,e_e000004,2304300003,4,0,NaN,NaN,NaN,NaN,NaN
2,e_e000004,2304300004,4,0,NaN,NaN,NaN,NaN,NaN
3,e_e000006,2304300005,1,0,NaN,소금빵,N,1,NaN
4,e_e000006,2304300007,1,0,NaN,쭈꾸미,N,1,NaN

### 방문지정보

,VISIT_AREA_ID,TRAVEL_ID,VISIT_ORDER,VISIT_AREA_NM,VISIT_START_YMD,VISIT_END_YMD,ROAD_NM_ADDR,LOTNO_ADDR,X_COORD,Y_COORD,...,POI_NM,RESIDENCE_TIME_MIN,VISIT_AREA_TYPE_CD,REVISIT_YN,VISIT_CHC_REASON_CD,LODGING_TYPE_CD,DGSTFN,REVISIT_INTENTION,RCMDTN_INTENTION,SGG_CD
0,2304300001,e_e000004,1,집,2023-04-30,2023-04-30,NaN,NaN,NaN,NaN,...,NaN,NaN,21,NaN,NaN,NaN,NaN,NaN,NaN,4.159012e+09
1,2304300002,e_e000004,2,화성 관광열차 안내소 연무대 매표소,2023-04-30,2023-04-30,경기 수원시 팔달구 창룡대로103번길 20,경기 수원시 팔달구 매향동 3-32,127.023339,37.287878,...,동대문종합시장 악세서리부자재시장,60.0,2,N,10.0,NaN,4.0,3.0,4.0,NaN
2,2304300003,e_e000004,3,창룡문,2023-04-30,2023-04-30,NaN,경기 수원시 팔달구 남수동,127.025143,37.287791,...,창룡문,30.0,2,N,1.0,NaN,4.0,4.0,4.0,NaN
3,2304300004,e_e000004,4,수원 화성 화홍문,2023-04-30,2023-04-30,NaN,경기 수원시 팔달구 북수동 9000-1,127.017626,37.287546,...,수원화성 화홍문,60.0,2,N,10.0,NaN,4.0,3.0,3.0,NaN
4,2304300005,e_e000004,5,집,2023-04-30,2023-05-01,NaN,NaN,NaN,NaN,...,NaN,390.0,21,NaN,NaN,NaN,NaN,NaN,NaN,4.159012e+09

- 여행 특성 나타내는 카테고리 종류 :  TRAVEL_PURPOSE, TRAVEL_MISSION, TRAVEL_MISSION_CHECK
- TRAVEL_PURPOSE와 TRAVEL_MISSION은 동일함, TRAVEL_MISSION_CHECK는 여러개의 카테고리를 가짐
- 정확한 차이는 찾지 못했으나 아마 TRAVEL_MISSION_CHECK가 실제로 여행한 특성을 더 많이 나타내는 듯  
- TRAVEL_MISSION_CHECK가 가장 데이터가 풍부하므로 이를 선택하는 게 좋을 듯

In [80]:
mission_map = {item["cd_b"]:item["cd_nm"] for _,item in c_codeb_df[c_codeb_df["cd_a"]=="MIS"].iterrows()}
print(mission_map)

{'1': '쇼핑', '2': '테마파크, 놀이시설, 동/식물원 방문', '3': '역사 유적지 방문', '4': '시티투어', '5': '야외 스포츠, 레포츠 활동', '6': '지역 문화예술/공연/전시시설 관람', '7': '유흥/오락(나이트라이프)', '8': '캠핑', '9': '지역 축제/이벤트 참가', '10': '온천/스파', '11': '교육/체험 프로그램 참가', '12': '드라마 촬영지 방문', '13': '종교/성지 순례', '21': 'Well-ness 여행', '22': 'SNS 인생샷 여행', '23': '호캉스 여행', '24': '신규 여행지 발굴', '25': '반려동물 동반 여행', '26': '인플루언서 따라하기 여행', '27': '친환경 여행(플로깅 여행)', '28': '등반 여행'}

- MIS 코드 분류 
~~~
{
    '1': '쇼핑', 
    '2': '테마파크, 놀이시설, 동/식물원 방문', 
    '3': '역사 유적지 방문', 
    '4': '시티투어', 
    '5': '야외 스포츠, 레포츠 활동', 
    '6': '지역 문화예술/공연/전시시설 관람', 
    '7': '유흥/오락(나이트라이프)', 
    '8': '캠핑', 
    '9': '지역 축제/이벤트 참가', 
    '10': '온천/스파', 
    '11': '교육/체험 프로그램 참가', 
    '12': '드라마 촬영지 방문', 
    '13': '종교/성지 순례', 
    '21': 'Well-ness 여행', 
    '22': 'SNS 인생샷 여행', 
    '23': '호캉스 여행', 
    '24': '신규 여행지 발굴', 
    '25': '반려동물 동반 여행', 
    '26': '인플루언서 따라하기 여행', 
    '27': '친환경 여행(플로깅 여행)', 
    '28': '등반 여행'}

~~~
- 야단법석 서비스 코드 분류 

~~~
mission_to_motive = {
    # 1. 지루한 일상 탈출
    "4": "지루한 일상 탈출",      # 시티투어
    "7": "지루한 일상 탈출",      # 유흥/오락

    # 2. 피로를 해소하는 휴식
    "10": "피로를 해소하는 휴식",  # 온천/스파
    "21": "피로를 해소하는 휴식",  # Well-ness 여행
    "23": "피로를 해소하는 휴식",  # 호캉스 여행

    # 3. 소중한 사람과의 추억
    "25": "소중한 사람과의 추억",  # 반려동물 동반 여행

    # 4. 나를 돌아보는 시간
    "13": "나를 돌아보는 시간",    # 종교/성지 순례
    "28": "나를 돌아보는 시간",    # 등반 여행

    # 5. 남는 건 사진 뿐
    "12": "남는 건 사진 뿐",       # 드라마 촬영지 방문
    "22": "남는 건 사진 뿐",       # SNS 인생샷 여행
    "26": "남는 건 사진 뿐",       # 인플루언서 따라하기 여행

    # 6. 액티비티로 활력 충전
    "2": "액티비티로 활력 충전",   # 테마파크, 놀이시설, 동/식물원 방문
    "5": "액티비티로 활력 충전",   # 야외 스포츠, 레포츠 활동
    "8": "액티비티로 활력 충전",   # 캠핑

    # 7. 낯선 곳에서의 설렘
    "9": "낯선 곳에서의 설렘",     # 지역 축제/이벤트 참가
    "11": "낯선 곳에서의 설렘",    # 교육/체험 프로그램 참가
    "24": "낯선 곳에서의 설렘",    # 신규 여행지 발굴
    "27": "낯선 곳에서의 설렘",    # 친환경 여행

    # 8. 우리 역사 문화 탐방
    "3": "우리 역사 문화 탐방",    # 역사 유적지 방문
    "6": "우리 역사 문화 탐방",    # 지역 문화예술/공연/전시시설 관람

    # 9. 특별한 기념일
    # 직접 대응되는 미션 코드는 약함. TRAVEL_MOTIVE 쪽 9번에 가까움.

    # 10. 발길이 이끄는 대로
    "1": "발길이 이끄는 대로",     # 쇼핑
}

~~~

In [ ]:
# 여행 계획 산출에 필요한 컬럼 
# TRAVEL_ID, VISIT_AREA_ID,VISIT_AREA_NM, VISIT_ORDER, CONTENT_ID, TRAVEL_PURPOSE, MTM (mission -> motive)

tn_mvmn_consume_his_이동수단소비내역_E.csv
<class 'pandas.DataFrame'>
RangeIndex: 4122 entries, 0 to 4121
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TRAVEL_ID        4122 non-null   str
 1   MVMN_SE          4122 non-null   int64
 2   PAYMENT_SE       4122 non-null   str
 3   PAYMENT_SEQ      4122 non-null   int64
 4   MVMN_SE_NM       4122 non-null   str
 5   RSVT_YN          4122 non-null   str
 6   PAYMENT_NUM      4122 non-null   int64
 7   BRNO             370 non-null    float64
 8   STORE_NM         378 non-null    str
 9   PAYMENT_DT       416 non-null    str
 10  PAYMENT_MTHD_SE  417 non-null    float64
 11  PAYMENT_AMT_WON  4122 non-null   int64
 12  PAYMENT_ETC      406 non-null    str
dtypes: float64(2), int64(4), str(7)
memory usage: 418.8 KB
None
=============
tn_activity_his_활동내역_E.csv
<class 'pandas.DataFrame'>
RangeIndex: 23689 entries, 0 to 23688
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   TRAVEL_ID          23689 non-null  str
 1   VISIT_AREA_ID      23689 non-null  int64
 2   ACTIVITY_TYPE_CD   23689 non-null  int64
 3   ACTIVITY_TYPE_SEQ  23689 non-null  int64
 4   ACTIVITY_ETC       0 non-null      float64
 5   ACTIVITY_DTL       14801 non-null  str
 6   RSVT_YN            14956 non-null  str
 7   EXPND_SE           14898 non-null  str
 8   ADMISSION_SE       3011 non-null   float64
dtypes: float64(2), int64(3), str(4)
memory usage: 1.6 MB
None
=============
tn_activity_consume_his_활동소비내역_E.csv
<class 'pandas.DataFrame'>
RangeIndex: 11739 entries, 0 to 11738
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   TRAVEL_ID          11739 non-null  str
 1   VISIT_AREA_ID      11739 non-null  int64
 2   ACTIVITY_TYPE_CD   11739 non-null  int64
 3   ACTIVITY_TYPE_SEQ  11739 non-null  int64
 4   CONSUME_HIS_SEQ    11739 non-null  int64
 5   CONSUME_HIS_SNO    11739 non-null  int64
 6   PAYMENT_NUM        11739 non-null  int64
 7   BRNO               9805 non-null   float64
 8   STORE_NM           11690 non-null  str
 9   ROAD_NM_ADDR       11390 non-null  str
 10  LOTNO_ADDR         7870 non-null   str
 11  ROAD_NM_CD         10242 non-null  float64
 12  LOTNO_CD           10242 non-null  float64
 13  PAYMENT_DT         10361 non-null  str
 14  PAYMENT_MTHD_SE    11739 non-null  int64
 15  PAYMENT_AMT_WON    11739 non-null  int64
 16  PAYMENT_ETC        8369 non-null   str
 17  SGG_CD             1319 non-null   float64
dtypes: float64(4), int64(8), str(6)
memory usage: 1.6 MB
None
=============
tn_lodge_consume_his_숙박소비내역_E.csv
<class 'pandas.DataFrame'>
RangeIndex: 745 entries, 0 to 744
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   TRAVEL_ID            745 non-null    str
 1   LODGING_NM           745 non-null    str
 2   LODGING_PAYMENT_SEQ  745 non-null    int64
 3   LODGING_TYPE_CD      745 non-null    int64
 4   RSVT_YN              745 non-null    str
 5   CHK_IN_DT_MIN        0 non-null      float64
 6   CHK_OUT_DT_MIN       0 non-null      float64
 7   PAYMENT_NUM          745 non-null    int64
 8   BRNO                 0 non-null      float64
 9   STORE_NM             462 non-null    str
 10  ROAD_NM_ADDR         674 non-null    str
 11  LOTNO_ADDR           501 non-null    str
 12  ROAD_NM_CD           406 non-null    float64
 13  LOTNO_CD             406 non-null    float64
 14  PAYMENT_DT           461 non-null    str
 15  PAYMENT_MTHD_SE      745 non-null    int64
 16  PAYMENT_AMT_WON      745 non-null    int64
 17  PAYMENT_ETC          426 non-null    str
dtypes: float64(5), int64(5), str(8)
memory usage: 104.9 KB
None
=============
tc_sgg_시군구코드.csv
<class 'pandas.DataFrame'>
RangeIndex: 8075 entries, 0 to 8074
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   SGG_CD   8075 non-null   int64
 1   SGG_CD1  8075 non-null   int64
 2   SGG_CD2  8058 non-null   float64
 3   SGG_CD3  7808 non-null   float64
 4   SGG_CD4  7808 non-null   float64
 5   SIDO_NM  8075 non-null   str
 6   SGG_NM   8025 non-null   str
 7   DONG_NM  7808 non-null   str
 8   RI_NM    2748 non-null   str
dtypes: float64(3), int64(2), str(4)
memory usage: 567.9 KB
None
=============
tc_codea_코드A.csv
<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   idx          30 non-null     int64
 1   cd_a         30 non-null     str
 2   cd_nm        30 non-null     str
 3   cd_memo      3 non-null      str
 4   cd_memo2     0 non-null      float64
 5   del_flag     30 non-null     str
 6   order_num    30 non-null     int64
 7   perm_write   30 non-null     str
 8   perm_edit    30 non-null     str
 9   perm_delete  30 non-null     str
 10  ins_dt       30 non-null     str
 11  edit_dt      0 non-null      float64
dtypes: float64(2), int64(2), str(8)
memory usage: 2.9 KB
None
=============
tn_travel_여행_E.csv
<class 'pandas.DataFrame'>
RangeIndex: 2560 entries, 0 to 2559
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   TRAVEL_ID             2560 non-null   str
 1   TRAVEL_NM             2560 non-null   str
 2   TRAVELER_ID           2560 non-null   str
 3   TRAVEL_PURPOSE        2560 non-null   str
 4   TRAVEL_START_YMD      2560 non-null   str
 5   TRAVEL_END_YMD        2560 non-null   str
 6   MVMN_NM               2244 non-null   str
 7   TRAVEL_PERSONA        2560 non-null   str
 8   TRAVEL_MISSION        2560 non-null   str
 9   TRAVEL_MISSION_CHECK  2560 non-null   str
dtypes: str(10)
memory usage: 200.1 KB
None
=============
tn_adv_consume_his_사전소비내역_E.csv
<class 'pandas.DataFrame'>
RangeIndex: 625 entries, 0 to 624
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TRAVEL_ID        625 non-null    str
 1   ADV_NM           625 non-null    str
 2   ADV_SEQ          625 non-null    int64
 3   PAYMENT_NUM      625 non-null    int64
 4   BRNO             372 non-null    float64
 5   STORE_NM         611 non-null    str
 6   ROAD_NM_ADDR     582 non-null    str
 7   LOTNO_ADDR       300 non-null    str
 8   ROAD_NM_CD       424 non-null    float64
 9   LOTNO_CD         424 non-null    float64
 10  PAYMENT_DT       432 non-null    str
 11  PAYMENT_MTHD_SE  625 non-null    int64
 12  PAYMENT_AMT_WON  625 non-null    int64
 13  PAYMENT_ETC      393 non-null    str
 14  SGG_CD           172 non-null    float64
dtypes: float64(4), int64(4), str(7)
memory usage: 73.4 KB
None
=============
tn_visit_area_info_방문지정보_E.csv
<class 'pandas.DataFrame'>
RangeIndex: 21384 entries, 0 to 21383
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   VISIT_AREA_ID        21384 non-null  int64
 1   TRAVEL_ID            21384 non-null  str
 2   VISIT_ORDER          21384 non-null  int64
 3   VISIT_AREA_NM        21384 non-null  str
 4   VISIT_START_YMD      21384 non-null  str
 5   VISIT_END_YMD        21384 non-null  str
 6   ROAD_NM_ADDR         18293 non-null  str
 7   LOTNO_ADDR           16044 non-null  str
 8   X_COORD              14486 non-null  float64
 9   Y_COORD              14486 non-null  float64
 10  ROAD_NM_CD           1338 non-null   float64
 11  LOTNO_CD             1338 non-null   float64
 12  POI_ID               14674 non-null  str
 13  POI_NM               14674 non-null  str
 14  RESIDENCE_TIME_MIN   18821 non-null  float64
 15  VISIT_AREA_TYPE_CD   21384 non-null  int64
 16  REVISIT_YN           15733 non-null  str
 17  VISIT_CHC_REASON_CD  15757 non-null  float64
 18  LODGING_TYPE_CD      1168 non-null   float64
 19  DGSTFN               15725 non-null  float64
 20  REVISIT_INTENTION    15725 non-null  float64
 21  RCMDTN_INTENTION     15725 non-null  float64
 22  SGG_CD               5391 non-null   float64
dtypes: float64(11), int64(3), str(9)
memory usage: 3.8 MB
None
=============
tn_tour_photo_관광사진_E.csv
<class 'pandas.DataFrame'>
RangeIndex: 14627 entries, 0 to 14626
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   TRAVEL_ID              14627 non-null  str
 1   VISIT_AREA_ID          14627 non-null  int64
 2   TOUR_PHOTO_SEQ         14627 non-null  int64
 3   PHOTO_FILE_ID          14627 non-null  str
 4   PHOTO_FILE_NM          14627 non-null  str
 5   PHOTO_FILE_FRMAT       14627 non-null  str
 6   PHOTO_FILE_DT          14627 non-null  str
 7   PHOTO_FILE_SAVE_PATH   14627 non-null  str
 8   PHOTO_FILE_RESOLUTION  14627 non-null  str
 9   PHOTO_FILE_X_COORD     14627 non-null  float64
 10  PHOTO_FILE_Y_COORD     14627 non-null  float64
 11  VISIT_AREA_NM          9315 non-null   str
dtypes: float64(2), int64(2), str(8)
memory usage: 1.3 MB
None
=============
tn_move_his_이동내역_E.csv
<class 'pandas.DataFrame'>
RangeIndex: 21384 entries, 0 to 21383
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   TRAVEL_ID            21384 non-null  str
 1   TRIP_ID              21384 non-null  int64
 2   START_VISIT_AREA_ID  2563 non-null   float64
 3   END_VISIT_AREA_ID    18821 non-null  float64
 4   START_DT_MIN         2563 non-null   str
 5   END_DT_MIN           18821 non-null  str
 6   MVMN_CD_1            18821 non-null  float64
 7   MVMN_CD_2            3344 non-null   float64
dtypes: float64(4), int64(1), str(3)
memory usage: 1.3 MB
None
=============
tn_companion_info_동반자정보_E.csv
<class 'pandas.DataFrame'>
RangeIndex: 3537 entries, 0 to 3536
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   COMPANION_SEQ        3537 non-null   int64
 1   TRAVEL_ID            3537 non-null   str
 2   REL_CD               3537 non-null   int64
 3   COMPANION_GENDER     3537 non-null   int64
 4   COMPANION_AGE_GRP    3537 non-null   int64
 5   COMPANION_SITUATION  3537 non-null   int64
dtypes: int64(5), str(1)
memory usage: 165.9 KB
None
=============
tn_traveller_master_여행객 Master_E.csv
<class 'pandas.DataFrame'>
RangeIndex: 2560 entries, 0 to 2559
Data columns (total 36 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   TRAVELER_ID                2560 non-null   str
 1   RESIDENCE_SGG_CD           2560 non-null   int64
 2   GENDER                     2560 non-null   str
 3   AGE_GRP                    2560 non-null   int64
 4   EDU_NM                     2560 non-null   int64
 5   EDU_FNSH_SE                2558 non-null   float64
 6   MARR_STTS                  2560 non-null   int64
 7   FAMILY_MEMB                2560 non-null   int64
 8   JOB_NM                     2560 non-null   int64
 9   JOB_ETC                    0 non-null      float64
 10  INCOME                     2560 non-null   int64
 11  HOUSE_INCOME               2004 non-null   float64
 12  TRAVEL_TERM                2560 non-null   int64
 13  TRAVEL_NUM                 2560 non-null   int64
 14  TRAVEL_LIKE_SIDO_1         2560 non-null   int64
 15  TRAVEL_LIKE_SGG_1          2560 non-null   int64
 16  TRAVEL_LIKE_SIDO_2         2560 non-null   int64
 17  TRAVEL_LIKE_SGG_2          2560 non-null   int64
 18  TRAVEL_LIKE_SIDO_3         2560 non-null   int64
 19  TRAVEL_LIKE_SGG_3          2560 non-null   int64
 20  TRAVEL_STYL_1              2560 non-null   int64
 21  TRAVEL_STYL_2              2560 non-null   int64
 22  TRAVEL_STYL_3              2560 non-null   int64
 23  TRAVEL_STYL_4              2560 non-null   int64
 24  TRAVEL_STYL_5              2560 non-null   int64
 25  TRAVEL_STYL_6              2560 non-null   int64
 26  TRAVEL_STYL_7              2560 non-null   int64
 27  TRAVEL_STYL_8              2560 non-null   int64
 28  TRAVEL_STATUS_RESIDENCE    2560 non-null   str
 29  TRAVEL_STATUS_DESTINATION  2560 non-null   str
 30  TRAVEL_STATUS_ACCOMPANY    2560 non-null   str
 31  TRAVEL_STATUS_YMD          2560 non-null   str
 32  TRAVEL_MOTIVE_1            2560 non-null   int64
 33  TRAVEL_MOTIVE_2            2463 non-null   float64
 34  TRAVEL_MOTIVE_3            2346 non-null   float64
 35  TRAVEL_COMPANIONS_NUM      2560 non-null   int64
dtypes: float64(5), int64(25), str(6)
memory usage: 720.1 KB
None
=============
tc_codeb_코드B.csv
<class 'pandas.DataFrame'>
RangeIndex: 238 entries, 0 to 237
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   idx        238 non-null    int64
 1   cd_a       238 non-null    str
 2   cd_b       238 non-null    str
 3   cd_nm      238 non-null    str
 4   cd_memo    2 non-null      str
 5   cd_memo2   0 non-null      float64
 6   del_flag   238 non-null    str
 7   order_num  238 non-null    int64
 8   ins_dt     238 non-null    str
 9   edit_dt    4 non-null      str
dtypes: float64(1), int64(2), str(7)
memory usage: 18.7 KB
None
=============

#### (c) 여행자 특성
- tn_traveller_master_여행객 Master_G.csv

In [82]:
# E,F,G 통합시키기 
traveler_df = concat_efg("tn_traveller_master_여행객 Master")
display(Markdown("### 여행자 특성"))
display(traveler_df.head())

### 여행자 특성

,TRAVELER_ID,RESIDENCE_SGG_CD,GENDER,AGE_GRP,EDU_NM,EDU_FNSH_SE,MARR_STTS,FAMILY_MEMB,JOB_NM,JOB_ETC,...,TRAVEL_STYL_7,TRAVEL_STYL_8,TRAVEL_STATUS_RESIDENCE,TRAVEL_STATUS_DESTINATION,TRAVEL_STATUS_ACCOMPANY,TRAVEL_STATUS_YMD,TRAVEL_MOTIVE_1,TRAVEL_MOTIVE_2,TRAVEL_MOTIVE_3,TRAVEL_COMPANIONS_NUM
0,e004720,41,여,60,4,1.0,3,3,11,NaN,...,5,5,경기도,서울,2인 가족 여행,2023-07-16~2023-07-16,2,6.0,NaN,1
1,e000914,30,여,20,6,1.0,1,1,3,NaN,...,4,1,대전광역시,서울,나홀로 여행,2023-06-03~2023-06-03,1,7.0,10.0,0
2,e003564,41,여,30,7,1.0,2,4,2,NaN,...,1,7,경기도,경기,자녀 동반 여행,2023-06-24~2023-06-24,8,3.0,7.0,3
3,e000396,41,여,30,6,1.0,2,2,2,NaN,...,1,6,경기도,인천,2인 가족 여행,2023-05-20~2023-05-21,9,1.0,7.0,1
4,e001890,11,남,20,6,1.0,1,4,3,NaN,...,5,6,서울특별시,경기,2인 여행(가족 외),2023-06-04~2023-06-04,3,1.0,5.0,1

In [83]:
traveler_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7680 entries, 0 to 7679
Data columns (total 36 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   TRAVELER_ID                7680 non-null   str
 1   RESIDENCE_SGG_CD           7680 non-null   int64
 2   GENDER                     7680 non-null   str
 3   AGE_GRP                    7680 non-null   int64
 4   EDU_NM                     7680 non-null   int64
 5   EDU_FNSH_SE                7678 non-null   float64
 6   MARR_STTS                  7680 non-null   int64
 7   FAMILY_MEMB                7680 non-null   int64
 8   JOB_NM                     7680 non-null   int64
 9   JOB_ETC                    0 non-null      float64
 10  INCOME                     7680 non-null   int64
 11  HOUSE_INCOME               5929 non-null   float64
 12  TRAVEL_TERM                7680 non-null   int64
 13  TRAVEL_NUM                 7680 non-null   int64
 14  TRAVEL_LIKE_SIDO_1         7680 non-null   int64
 15  TRAVEL_LIKE_SGG_1          7680 non-null   int64
 16  TRAVEL_LIKE_SIDO_2         7680 non-null   int64
 17  TRAVEL_LIKE_SGG_2          7680 non-null   int64
 18  TRAVEL_LIKE_SIDO_3         7680 non-null   int64
 19  TRAVEL_LIKE_SGG_3          7680 non-null   int64
 20  TRAVEL_STYL_1              7680 non-null   int64
 21  TRAVEL_STYL_2              7680 non-null   int64
 22  TRAVEL_STYL_3              7680 non-null   int64
 23  TRAVEL_STYL_4              7680 non-null   int64
 24  TRAVEL_STYL_5              7680 non-null   int64
 25  TRAVEL_STYL_6              7680 non-null   int64
 26  TRAVEL_STYL_7              7680 non-null   int64
 27  TRAVEL_STYL_8              7680 non-null   int64
 28  TRAVEL_STATUS_RESIDENCE    7680 non-null   str
 29  TRAVEL_STATUS_DESTINATION  7680 non-null   str
 30  TRAVEL_STATUS_ACCOMPANY    7680 non-null   str
 31  TRAVEL_STATUS_YMD          7680 non-null   str
 32  TRAVEL_MOTIVE_1            7680 non-null   int64
 33  TRAVEL_MOTIVE_2            7413 non-null   float64
 34  TRAVEL_MOTIVE_3            7076 non-null   float64
 35  TRAVEL_COMPANIONS_NUM      7680 non-null   int64
dtypes: float64(5), int64(25), str(6)
memory usage: 2.1 MB

In [84]:
# RESIDENCE_SGG_CD	GENDER	AGE_GRP	EDU_NM
# TRAVEL_STYL_7	TRAVEL_STYL_8왜 나뉘는..????? 
# TRAVEL_STATUS_DESTINATION를 테마 여행 지표로 간주해도 될까? 
# TRAVEL_COMPANIONS_NUM
# TRAVEL_MOTIVE_1, TRAVEL_MOTIVE_2, TRAVEL_MOTIVE_3 가 뭐지 
# 회원가입 온보딩 : 거주 지역 / 여행 스타일 /선호 여행 지역 / 성별 
# 여행 온보딩 : barrier 조건 (아이 동반/어르신 동반/휠체어 이용) / 여행의 동기(10개) / 동반자 최대 2

## 2. Preprocess

### (1) 지역 테마 여행 전처리
* 목표 : 서울, 인천, 대전, 수원, 광주, 부산, 대구, 창원 지역별 여행 별도의 df로 분리

### (2) 방문지 정보 전처리
* 목표 : visit_area_id와 contentid 매칭시키기

### (3) 방문자 정보 전처리
* 목표 : 동행자, 방문자 특징 추출해 지역별 csv 파일 정리

## 3. Visualization